<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ChangelogsTableSeeder extends Seeder
{
    /**
     * Pobla el changelog con el histórico de PRs del repositorio.
     */
    public function run(): void
    {
        DB::table('changelogs')->delete();

        $changelogs = [
            [
                'id' => 1,
                'title' => 'PR #45: docs: documentar dependencias e instalación',
                'description' => 'docs: documentar dependencias e instalación',
                'body' => '<p><strong>PR #45</strong>: docs: documentar dependencias e instalación</p><p>Merge pull request #45 from tiendaweb/codex/add-dependencies-and-installation-sections-to-readme.md</p>',
                'created_at' => '2025-11-20 05:31:22',
                'updated_at' => '2025-11-20 05:31:22',
            ],
            [
                'id' => 2,
                'title' => 'PR #46: Ajusta migraciones de categoria_producto',
                'description' => 'Ajusta migraciones de categoria_producto',
                'body' => '<p><strong>PR #46</strong>: Ajusta migraciones de categoria_producto</p><p>Merge pull request #46 from tiendaweb/codex/consolidar-migracion-de-categoria_producto</p>',
                'created_at' => '2025-11-20 05:33:28',
                'updated_at' => '2025-11-20 05:33:28',
            ],
            [
                'id' => 3,
                'title' => 'PR #47: fix: protege datos de perfil al ejecutar ProductosSeeder',
                'description' => 'fix: protege datos de perfil al ejecutar ProductosSeeder',
                'body' => '<p><strong>PR #47</strong>: fix: protege datos de perfil al ejecutar ProductosSeeder</p><p>Merge pull request #47 from tiendaweb/codex/update-productosseeder-behavior</p>',
                'created_at' => '2025-11-20 05:34:21',
                'updated_at' => '2025-11-20 05:34:21',
            ],
            [
                'id' => 4,
                'title' => 'PR #48: feat: configurar plan de premios de liderazgo',
                'description' => 'feat: configurar plan de premios de liderazgo',
                'body' => '<p><strong>PR #48</strong>: feat: configurar plan de premios de liderazgo</p><p>Merge pull request #48 from tiendaweb/codex/create-migrations-and-eloquent-models-for-awards</p>',
                'created_at' => '2025-11-20 05:57:11',
                'updated_at' => '2025-11-20 05:57:11',
            ],
            [
                'id' => 5,
                'title' => 'PR #49: feat: gestiona rangos y cierres de campaña en Volt',
                'description' => 'feat: gestiona rangos y cierres de campaña en Volt',
                'body' => '<p><strong>PR #49</strong>: feat: gestiona rangos y cierres de campaña en Volt</p><p>Merge pull request #49 from tiendaweb/codex/create-volt-components-for-crud-operations</p>',
                'created_at' => '2025-11-20 06:05:54',
                'updated_at' => '2025-11-20 06:05:54',
            ],
            [
                'id' => 6,
                'title' => 'PR #50: feat: ajusta paleta azul secundaria y enlaces base',
                'description' => 'feat: ajusta paleta azul secundaria y enlaces base',
                'body' => '<p><strong>PR #50</strong>: feat: ajusta paleta azul secundaria y enlaces base</p><p>Merge pull request #50 from tiendaweb/codex/add-css-variable-block-for-blue-palette</p>',
                'created_at' => '2025-11-20 11:13:02',
                'updated_at' => '2025-11-20 11:13:02',
            ],
            [
                'id' => 7,
                'title' => 'PR #51: Actualiza estilos primario y secundario de botones del panel',
                'description' => 'Actualiza estilos primario y secundario de botones del panel',
                'body' => '<p><strong>PR #51</strong>: Actualiza estilos primario y secundario de botones del panel</p><p>Merge pull request #51 from tiendaweb/codex/update-component-styles-for-themes</p>',
                'created_at' => '2025-11-20 11:15:00',
                'updated_at' => '2025-11-20 11:15:00',
            ],
            [
                'id' => 8,
                'title' => 'PR #52: style: adapta dashboard a paleta corporativa',
                'description' => 'style: adapta dashboard a paleta corporativa',
                'body' => '<p><strong>PR #52</strong>: style: adapta dashboard a paleta corporativa</p><p>Merge pull request #52 from tiendaweb/codex/update-theme-colors-in-dashboard</p>',
                'created_at' => '2025-11-20 11:17:54',
                'updated_at' => '2025-11-20 11:17:54',
            ],
            [
                'id' => 9,
                'title' => 'PR #53: feat: agrega sistema de cobros y pagos por campaña',
                'description' => 'feat: agrega sistema de cobros y pagos por campaña',
                'body' => '<p><strong>PR #53</strong>: feat: agrega sistema de cobros y pagos por campaña</p><p>Merge pull request #53 from tiendaweb/codex/implementar-sistema-de-cobros-y-pagos</p>',
                'created_at' => '2025-11-20 11:24:52',
                'updated_at' => '2025-11-20 11:24:52',
            ],
            [
                'id' => 10,
                'title' => 'PR #54: feat: agrega página de perfil inspirada en onboarding',
                'description' => 'feat: agrega página de perfil inspirada en onboarding',
                'body' => '<p><strong>PR #54</strong>: feat: agrega página de perfil inspirada en onboarding</p><p>Merge pull request #54 from tiendaweb/codex/create-perfil-page-and-adjust-sidebar</p>',
                'created_at' => '2025-11-20 11:33:56',
                'updated_at' => '2025-11-20 11:33:56',
            ],
            [
                'id' => 11,
                'title' => 'PR #55: Restringe vendedora y líder al usuario autenticado en creación de pedidos',
                'description' => 'Restringe vendedora y líder al usuario autenticado en creación de pedidos',
                'body' => '<p><strong>PR #55</strong>: Restringe vendedora y líder al usuario autenticado en creación de pedidos</p><p>Merge pull request #55 from tiendaweb/codex/implementar-gestion-de-roles-en-crear-pedido</p>',
                'created_at' => '2025-11-20 11:42:18',
                'updated_at' => '2025-11-20 11:42:18',
            ],
            [
                'id' => 12,
                'title' => 'PR #56: Restringe la selección de vendedoras por líder en la creación de pedidos',
                'description' => 'Restringe la selección de vendedoras por líder en la creación de pedidos',
                'body' => '<p><strong>PR #56</strong>: Restringe la selección de vendedoras por líder en la creación de pedidos</p><p>Merge pull request #56 from tiendaweb/codex/implementar-logica-de-rol-de-lider</p>',
                'created_at' => '2025-11-20 11:54:57',
                'updated_at' => '2025-11-20 11:54:57',
            ],
            [
                'id' => 13,
                'title' => 'PR #57: Eliminar columna de descuento en factura de pedidos',
                'description' => 'Eliminar columna de descuento en factura de pedidos',
                'body' => '<p><strong>PR #57</strong>: Eliminar columna de descuento en factura de pedidos</p><p>Merge pull request #57 from tiendaweb/codex/remove-%-desc-column-from-factura</p>',
                'created_at' => '2025-11-20 13:26:32',
                'updated_at' => '2025-11-20 13:26:32',
            ],
            [
                'id' => 14,
                'title' => 'PR #58: fix: usa datos de vendedora en pie de factura',
                'description' => 'fix: usa datos de vendedora en pie de factura',
                'body' => '<p><strong>PR #58</strong>: fix: usa datos de vendedora en pie de factura</p><p>Merge pull request #58 from tiendaweb/codex/update-footer-label-to-vendedora</p>',
                'created_at' => '2025-11-20 13:36:09',
                'updated_at' => '2025-11-20 13:36:09',
            ],
            [
                'id' => 15,
                'title' => 'PR #59: fix: ajusta tabla de factura sin columna de descuento',
                'description' => 'fix: ajusta tabla de factura sin columna de descuento',
                'body' => '<p><strong>PR #59</strong>: fix: ajusta tabla de factura sin columna de descuento</p><p>Merge pull request #59 from tiendaweb/codex/remove-%-desc.-header-and-cell</p>',
                'created_at' => '2025-11-20 13:43:18',
                'updated_at' => '2025-11-20 13:43:18',
            ],
            [
                'id' => 16,
                'title' => 'PR #60: Documenta funciones de cobros y pagos',
                'description' => 'Documenta funciones de cobros y pagos',
                'body' => '<p><strong>PR #60</strong>: Documenta funciones de cobros y pagos</p><p>Merge pull request #60 from tiendaweb/codex/verificar-y-corregir-documentacion</p>',
                'created_at' => '2025-11-20 14:05:17',
                'updated_at' => '2025-11-20 14:05:17',
            ],
            [
                'id' => 17,
                'title' => 'PR #61: feat: dashboard dinámico por rol',
                'description' => 'feat: dashboard dinámico por rol',
                'body' => '<p><strong>PR #61</strong>: feat: dashboard dinámico por rol</p><p>Merge pull request #61 from tiendaweb/codex/crear-dashboard-dinamico-por-rol-con-gamificacion</p>',
                'created_at' => '2025-11-20 14:26:13',
                'updated_at' => '2025-11-20 14:26:13',
            ],
            [
                'id' => 18,
                'title' => 'PR #62: docs: agrega mock de dashboard',
                'description' => 'docs: agrega mock de dashboard',
                'body' => '<p><strong>PR #62</strong>: docs: agrega mock de dashboard</p><p>Merge pull request #62 from tiendaweb/codex/crear-dashboard-dinamico-por-rol-con-gamificacion-p8zp2n</p>',
                'created_at' => '2025-11-20 14:36:54',
                'updated_at' => '2025-11-20 14:36:54',
            ],
            [
                'id' => 19,
                'title' => 'PR #63: feat: alinea plan de premios al esquema real de AlmaMia',
                'description' => 'feat: alinea plan de premios al esquema real de AlmaMia',
                'body' => '<p><strong>PR #63</strong>: feat: alinea plan de premios al esquema real de AlmaMia</p><p>Merge pull request #63 from tiendaweb/codex/refactorizar-plan-de-premios-en-laravel</p>',
                'created_at' => '2025-11-20 14:40:09',
                'updated_at' => '2025-11-20 14:40:09',
            ],
            [
                'id' => 20,
                'title' => 'PR #64: Refactor de esquema de rangos de líderes',
                'description' => 'Refactor de esquema de rangos de líderes',
                'body' => '<p><strong>PR #64</strong>: Refactor de esquema de rangos de líderes</p><p>Merge pull request #64 from tiendaweb/codex/actualizar-migracion-de-rangos_lideres</p>',
                'created_at' => '2025-11-20 15:12:03',
                'updated_at' => '2025-11-20 15:12:03',
            ],
            [
                'id' => 21,
                'title' => 'PR #65: Simplifica estructura de premio_reglas y semillas',
                'description' => 'Simplifica estructura de premio_reglas y semillas',
                'body' => '<p><strong>PR #65</strong>: Simplifica estructura de premio_reglas y semillas</p><p>Merge pull request #65 from tiendaweb/codex/migrate-premioregla-table-structure-and-data</p>',
                'created_at' => '2025-11-20 15:25:34',
                'updated_at' => '2025-11-20 15:25:34',
            ],
            [
                'id' => 22,
                'title' => 'PR #66: feat: agrega catalogos con coordenadas relativas',
                'description' => 'feat: agrega catalogos con coordenadas relativas',
                'body' => '<p><strong>PR #66</strong>: feat: agrega catalogos con coordenadas relativas</p><p>Merge pull request #66 from tiendaweb/codex/generate-migrations-and-models-for-catalogos</p>',
                'created_at' => '2025-11-20 15:34:40',
                'updated_at' => '2025-11-20 15:34:40',
            ],
            [
                'id' => 23,
                'title' => 'PR #67: feat: ajusta métricas de liderazgo',
                'description' => 'feat: ajusta métricas de liderazgo',
                'body' => '<p><strong>PR #67</strong>: feat: ajusta métricas de liderazgo</p><p>Merge pull request #67 from tiendaweb/codex/create-migration-for-activity-metrics-update</p>',
                'created_at' => '2025-11-20 15:36:32',
                'updated_at' => '2025-11-20 15:36:32',
            ],
            [
                'id' => 24,
                'title' => 'PR #68: Normaliza seeders de premios y agrega fixture de métricas',
                'description' => 'Normaliza seeders de premios y agrega fixture de métricas',
                'body' => '<p><strong>PR #68</strong>: Normaliza seeders de premios y agrega fixture de métricas</p><p>Merge pull request #68 from tiendaweb/codex/adjust-range-inserts-and-restructure-prize-rules</p>',
                'created_at' => '2025-11-20 15:42:26',
                'updated_at' => '2025-11-20 15:42:26',
            ],
            [
                'id' => 25,
                'title' => 'PR #69: feat: agrega visor de catálogo con slider',
                'description' => 'feat: agrega visor de catálogo con slider',
                'body' => '<p><strong>PR #69</strong>: feat: agrega visor de catálogo con slider</p><p>Merge pull request #69 from tiendaweb/codex/crear-pagina-de-catalogo-en-blade</p>',
                'created_at' => '2025-11-20 15:46:44',
                'updated_at' => '2025-11-20 15:46:44',
            ],
            [
                'id' => 26,
                'title' => 'PR #70: feat: calcular premios de liderazgo por campaña',
                'description' => 'feat: calcular premios de liderazgo por campaña',
                'body' => '<p><strong>PR #70</strong>: feat: calcular premios de liderazgo por campaña</p><p>Merge pull request #70 from tiendaweb/codex/create-premioslidercalculator-service</p>',
                'created_at' => '2025-11-20 15:55:22',
                'updated_at' => '2025-11-20 15:55:22',
            ],
            [
                'id' => 27,
                'title' => 'PR #71: Refactoriza pedidos compartiendo servicio y script común',
                'description' => 'Refactoriza pedidos compartiendo servicio y script común',
                'body' => '<p><strong>PR #71</strong>: Refactoriza pedidos compartiendo servicio y script común</p><p>Merge pull request #71 from tiendaweb/codex/crear-servicio-compartido-para-gestion-de-pedidos</p>',
                'created_at' => '2025-11-20 16:04:26',
                'updated_at' => '2025-11-20 16:04:26',
            ],
            [
                'id' => 28,
                'title' => 'PR #72: feat: crea panel admin para catalogo',
                'description' => 'feat: crea panel admin para catalogo',
                'body' => '<p><strong>PR #72</strong>: feat: crea panel admin para catalogo</p><p>Merge pull request #72 from tiendaweb/codex/define-web-routes-for-crud-catalogo</p>',
                'created_at' => '2025-11-20 17:22:18',
                'updated_at' => '2025-11-20 17:22:18',
            ],
            [
                'id' => 29,
                'title' => 'PR #73: feat: dashboard de reportes AlmaMia para admin',
                'description' => 'feat: dashboard de reportes AlmaMia para admin',
                'body' => '<p><strong>PR #73</strong>: feat: dashboard de reportes AlmaMia para admin</p><p>Merge pull request #73 from tiendaweb/codex/create-report-page-for-almamia</p>',
                'created_at' => '2025-11-20 18:34:47',
                'updated_at' => '2025-11-20 18:34:47',
            ],
            [
                'id' => 30,
                'title' => 'PR #74: Evita conflictos de seeders en instalaciones nuevas',
                'description' => 'Evita conflictos de seeders en instalaciones nuevas',
                'body' => '<p><strong>PR #74</strong>: Evita conflictos de seeders en instalaciones nuevas</p><p>Merge pull request #74 from tiendaweb/codex/ensure-seeders-do-not-conflict</p>',
                'created_at' => '2025-11-20 20:50:15',
                'updated_at' => '2025-11-20 20:50:15',
            ],
            [
                'id' => 31,
                'title' => 'PR #75: Ajusta seeders y migraciones para compatibilidad con SQLite',
                'description' => 'Ajusta seeders y migraciones para compatibilidad con SQLite',
                'body' => '<p><strong>PR #75</strong>: Ajusta seeders y migraciones para compatibilidad con SQLite</p><p>Merge pull request #75 from tiendaweb/codex/refactor-database-seeders-for-psr-4-compliance</p>',
                'created_at' => '2025-11-20 22:28:49',
                'updated_at' => '2025-11-20 22:28:49',
            ],
            [
                'id' => 32,
                'title' => 'PR #76: Validación de autoload y pautas de despliegue',
                'description' => 'Validación de autoload y pautas de despliegue',
                'body' => '<p><strong>PR #76</strong>: Validación de autoload y pautas de despliegue</p><p>Merge pull request #76 from tiendaweb/codex/add-existence-check-for-autoload-file</p>',
                'created_at' => '2025-11-20 22:34:18',
                'updated_at' => '2025-11-20 22:34:18',
            ],
            [
                'id' => 33,
                'title' => 'PR #77: Configura pipeline de build de assets y consumo de compilados',
                'description' => 'Configura pipeline de build de assets y consumo de compilados',
                'body' => '<p><strong>PR #77</strong>: Configura pipeline de build de assets y consumo de compilados</p><p>Merge pull request #77 from tiendaweb/codex/configure-ci/cd-pipeline-for-build-artifacts</p>',
                'created_at' => '2025-11-20 22:48:46',
                'updated_at' => '2025-11-20 22:48:46',
            ],
            [
                'id' => 34,
                'title' => 'PR #78: Agregar endpoint de salud y excepción de mantenimiento',
                'description' => 'Agregar endpoint de salud y excepción de mantenimiento',
                'body' => '<p><strong>PR #78</strong>: Agregar endpoint de salud y excepción de mantenimiento</p><p>Merge pull request #78 from tiendaweb/codex/verificar-y-reparar-error-503</p>',
                'created_at' => '2025-11-20 23:04:58',
                'updated_at' => '2025-11-20 23:04:58',
            ],
            [
                'id' => 35,
                'title' => 'PR #79: Eliminar referencias a Vite en tema Anchor',
                'description' => 'Eliminar referencias a Vite en tema Anchor',
                'body' => '<p><strong>PR #79</strong>: Eliminar referencias a Vite en tema Anchor</p><p>Merge pull request #79 from tiendaweb/codex/remove-vite-logic-from-anchor-theme</p>',
                'created_at' => '2025-11-20 23:40:50',
                'updated_at' => '2025-11-20 23:40:50',
            ],
            [
                'id' => 36,
                'title' => 'PR #80: Docs: actualiza gestión de assets sin Vite',
                'description' => 'Docs: actualiza gestión de assets sin Vite',
                'body' => '<p><strong>PR #80</strong>: Docs: actualiza gestión de assets sin Vite</p><p>Merge pull request #80 from tiendaweb/codex/update-documentation-to-remove-vite-reference</p>',
                'created_at' => '2025-11-20 23:45:14',
                'updated_at' => '2025-11-20 23:45:14',
            ],
            [
                'id' => 37,
                'title' => 'PR #81: Agrega enlace a componentes nuevos en el sidebar',
                'description' => 'Agrega enlace a componentes nuevos en el sidebar',
                'body' => '<p><strong>PR #81</strong>: Agrega enlace a componentes nuevos en el sidebar</p><p>Merge pull request #81 from tiendaweb/codex/add-new-items-link-to-sidebar</p>',
                'created_at' => '2025-11-21 01:49:02',
                'updated_at' => '2025-11-21 01:49:02',
            ],
            [
                'id' => 38,
                'title' => 'PR #82: feat: agrega vistas de cobros y pagos',
                'description' => 'feat: agrega vistas de cobros y pagos',
                'body' => '<p><strong>PR #82</strong>: feat: agrega vistas de cobros y pagos</p><p>Merge pull request #82 from tiendaweb/codex/implementar-sistema-de-cobros-y-pagos-pdqjkj</p>',
                'created_at' => '2025-11-21 04:55:07',
                'updated_at' => '2025-11-21 04:55:07',
            ],
            [
                'id' => 39,
                'title' => 'PR #83: Añade páginas de ajustes para CSS y JS personalizados',
                'description' => 'Añade páginas de ajustes para CSS y JS personalizados',
                'body' => '<p><strong>PR #83</strong>: Añade páginas de ajustes para CSS y JS personalizados</p><p>Merge pull request #83 from tiendaweb/codex/add-custom-css-and-js-settings-pages</p>',
                'created_at' => '2025-11-21 14:50:06',
                'updated_at' => '2025-11-21 14:50:06',
            ],
            [
                'id' => 40,
                'title' => 'PR #84: Agrega inyección de CSS y JS personalizados en el tema Anchor',
                'description' => 'Agrega inyección de CSS y JS personalizados en el tema Anchor',
                'body' => '<p><strong>PR #84</strong>: Agrega inyección de CSS y JS personalizados en el tema Anchor</p><p>Merge pull request #84 from tiendaweb/codex/add-custom-css-and-js-settings</p>',
                'created_at' => '2025-11-21 15:40:51',
                'updated_at' => '2025-11-21 15:40:51',
            ],
            [
                'id' => 41,
                'title' => 'PR #85: Corrige visibilidad del botón flotante en catálogo',
                'description' => 'Corrige visibilidad del botón flotante en catálogo',
                'body' => '<p><strong>PR #85</strong>: Corrige visibilidad del botón flotante en catálogo</p><p>Merge pull request #85 from tiendaweb/codex/reparar-boton-flotante-en-catalogo</p>',
                'created_at' => '2025-11-22 00:38:51',
                'updated_at' => '2025-11-22 00:38:51',
            ],
            [
                'id' => 42,
                'title' => 'PR #86: Ajusta visor de catálogo y botón flotante',
                'description' => 'Ajusta visor de catálogo y botón flotante',
                'body' => '<p><strong>PR #86</strong>: Ajusta visor de catálogo y botón flotante</p><p>Merge pull request #86 from tiendaweb/codex/fix-floating-cart-icon-size</p>',
                'created_at' => '2025-11-22 00:50:58',
                'updated_at' => '2025-11-22 00:50:58',
            ],
            [
                'id' => 43,
                'title' => 'PR #87: Ajusta botón flotante del catálogo',
                'description' => 'Ajusta botón flotante del catálogo',
                'body' => '<p><strong>PR #87</strong>: Ajusta botón flotante del catálogo</p><p>Merge pull request #87 from tiendaweb/codex/update-floating-button-styles-and-animations</p>',
                'created_at' => '2025-11-22 01:08:30',
                'updated_at' => '2025-11-22 01:08:30',
            ],
        ];

        DB::table('changelogs')->insert($changelogs);
    }
}
